### ISSUE TITLE
YouTube speaking template issues

### ISSUE THREAD

**Issue by adamfast** [djangocon/2024.djangocon.us#127]
https://2024.djangocon.us/speaking/youtube/

Jeff's screenshot on the original PR (https://github.com/djangocon/2024.djangocon.us/pull/126) shows copy to clipboard for both title and the text box, and those aren't showing on the actual page.

Secondly, when I click "copy to clipboard" on any video besides the first, it highlights and copies the text in the first box so the button is targeting the wrong textbox I think?

**Comment by adamfast** [comment]
The titles here are awkward too - we wouldn't want Sep 23 8:30 am EDT to be the title for YouTube. Last year it looked more like "<title> with <speaker(s)>"

Examples:
- Swiss Army Django: Small Footprint ETL with Noah Kantrowitz
- Meet-ups: A Grand Vision for a Humble Endeavor with Deb Nicholson
- Hosting and DevOps for Django with Benjamin "Zags" Zagorsky

**Comment by tim-schilling** [comment]
Not sure where the other copy button went or why it's copying the wrong thing.

Regarding the title aspect, we did that manually last year. The format in this year's matches last years on the speaking/youtube page. https://2023.djangocon.us/speaking/youtube/

I can try to take a look at this tonight.

**Comment by jefftriplett** [comment]
I wonder if we need to do something to rebuild the assets. This looks like it's not seeing my styles.

**Comment by tim-schilling** [comment]
To clarify, I will improve the title to match what we want in YouTube.

**Comment by jefftriplett** [comment]
Layout is mostly fixed https://2024.djangocon.us/speaking/youtube/ 

You might try a hard refresh if the buttons aren't lining up.

**Comment by jefftriplett** [comment]
@adamfast @tim-schilling Let me know if we need another title change, my changes only copy the talk name like `Keynote - Power to the People who Teach the People` even though you see the date. I put the talk name in its own element which does not copy the date/time.

**Comment by tim-schilling** [comment]
Unfortunately we need to put the presenter's name in the title text, such as "Swiss Army Django: Small Footprint ETL with Noah Kantrowitz"

**Comment by jefftriplett** [comment]
@tim-schilling good catch, this is now captured in https://github.com/djangocon/2024.djangocon.us/issues/130
