### ISSUE TITLE
Add speaker to youtube titles

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2024.djangocon.us#130]
> The titles here are awkward too - we wouldn't want Sep 23 8:30 am EDT to be the title for YouTube. Last year it looked more like "<title> with <speaker(s)>"

> Examples:
> - Swiss Army Django: Small Footprint ETL with Noah Kantrowitz
> - Meet-ups: A Grand Vision for a Humble Endeavor with Deb Nicholson
> - Hosting and DevOps for Django with Benjamin "Zags" Zagorsky

_Originally posted by @adamfast in https://github.com/djangocon/2024.djangocon.us/issues/127#issuecomment-2427763227_
            
Note: Some talks have more than one speaker, but we have a limited number of characters on YouTube, which most likely means they won't all fit. The description should capture the rest.

**Comment by jefftriplett** [comment]
Fixed by #129

**Comment by tim-schilling** [comment]
My bad. I should have been up front that I was fixing it.

**Comment by jefftriplett** [comment]
@tim-schilling all good. I thought I looked, but no time was wasted. In some good news, I used the time to figure out why the website wouldn't run on my Mac Mini.
