### ISSUE TITLE
Speaker resources page needs a content update

### ISSUE THREAD

**Issue by drewbrew** [djangocon/2024.djangocon.us#16]
2 commits:
- https://github.com/djangocon/2024-old.djangocon.us/commit/1fe7331e3e33aeba9a72f311a0a943481d699c41
- https://github.com/djangocon/2024-old.djangocon.us/commit/787e150d2c1f307e96214d1f8a73f746de3f3d9c

**Comment by sodevious** [comment]
should be fixed here https://github.com/djangocon/2024.djangocon.us/commit/3b0e840a576f8d78a34d0bfb9b7649880d298d50

**Comment by drewbrew** [comment]
At first glance, that looks ok to me. @emullaney would you mind taking a second look just in case?

**Comment by emullaney** [comment]
FYI @sodevious @drewbrew I added comments to [that commit](https://github.com/djangocon/2024.djangocon.us/commit/3b0e840a576f8d78a34d0bfb9b7649880d298d50).
