### ISSUE TITLE
Add sitemap.xml

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2024.djangocon.us#5]

**Comment by mtrythall** [comment]
Have one here now: https://2024.djangocon.us/sitemap.xml

Pretty basic. LMK if it should do more.

Note that the generation is a little clunky. We exclude /presenters/ which are speaker cards, for obvious reasons. If there are more exceptions we'll want to move some logic elsewhere.

**Comment by mtrythall** [comment]
Assigning to @jefftriplett to confirm and close, since he filed.

**Comment by jefftriplett** [comment]
I'm surprised they don't have a built-in way of doing these. Then again, https://www.11ty.dev/sitemap.xml gives me a 404. 

Is it possible to keep the `sitemap: false` frontmatter that we had before? To clarify, the default is to include everything unless `sitemap: false` is set? 

We used that quite a bit to control when certain pages get released, and it was a Jekyll/GitHub Pages built in behavior.

**Comment by jefftriplett** [comment]
I think we'll need that opt-out on a page by page basis. 

Depending on how the schedule is structured, we tend to have lots of noise from pages that are filler that don't need to be in a sitemap. 

We run into this with the alternative homepages with the coming soon and recap pages too.

**Comment by mtrythall** [comment]
Sounds good. I'll wire this up.

**Comment by mtrythall** [comment]
`sitemap: false` does the trick.
