### ISSUE TITLE
Improve focus indicators

### ISSUE THREAD

**Issue by SaptakS** [djangocon/2024.djangocon.us#56]
Right now the focus indicator for interactive elements in the page is left to the browser default. However, the browser defaults don't always meet the accessibility requirements, so it might be better to add a custom focus indicator. 

For example, in chrome, this is the focus state of the buttons:
![image](https://github.com/user-attachments/assets/1d7ce5cc-9c34-45c7-983a-c6ec3cf90cdf)
And, that is pretty indistinguishable from the non-focused element. 

So I think adding a [custom focus indicator](https://www.sarasoueidan.com/blog/focus-indicators/), which follows the WCAG guidelines might be better for accessibility purposes.

**Comment by mtrythall** [comment]
Hi. I added some big ol' focus indicators.

Went with red so it'd really standout against all the blue, but it's easily changed. Mostly focused on tabbing, not so much click. I think that works for now.

<img width="209" alt="Screenshot 2024-09-01 at 4 28 17 PM" src="https://github.com/user-attachments/assets/61b3d52c-dfb2-4769-aa71-17cb3e36ee54">
<img width="435" alt="Screenshot 2024-09-01 at 4 28 10 PM" src="https://github.com/user-attachments/assets/92e7fd72-865e-4a1c-8d1a-8de045b2e7cb">
<img width="618" alt="Screenshot 2024-09-01 at 4 29 07 PM" src="https://github.com/user-attachments/assets/89de0a53-065c-4829-a744-a87a802fa75a">

**Comment by mtrythall** [comment]
Closing for now. Can revisit in a future, accessibility focused effort. If you spot an issue, feel free to raise it.

**Comment by SaptakS** [comment]
I think only showing on tabbing is fine, and I think the bold red looks nice. Looks good to me.
