### ISSUE TITLE
Add a skip link

### ISSUE THREAD

**Issue by SaptakS** [djangocon/2024.djangocon.us#57]
Under [WCAG Success Criterion 2.4.1](https://www.w3.org/WAI/WCAG22/Understanding/bypass-blocks.html), it is recommended to provide a way for the user to skip the parts that are repeated in every page (e.g. navigation) and jump to the primary content of the web page. 

Given the navigation for the https://2024.djangocon.us/ is decent big, I think adding a skip link at the very beginning will help improve the accessibility of the website. It will allow screenreader users and keyboard users to jump directly to the primary content instead of tabbing through the entire main navigation. The skip link can be made only visible when focused to avoid any design concerns.

Refs: https://webaim.org/techniques/skipnav/

**Comment by mtrythall** [comment]
Good call. We'll get this in.

**Comment by mtrythall** [comment]
This is in. I added a button right after the body opening tag. It only appears on focus, but is off screen so screen readers should pick it up.

<img width="711" alt="Screenshot 2024-08-04 at 3 33 24 PM" src="https://github.com/user-attachments/assets/6028a2ea-841c-493d-abfa-a9faa856f0f6">
