### ISSUE TITLE
Create ride/room share page

### ISSUE THREAD

**Issue by tim-schilling** [djangocon/2024.djangocon.us#61]
The new site design didn't include a page for the ride and room sharing page that we've had in the past. It's probably a good idea to add it.
- https://2023.djangocon.us/room-sharing/
- https://github.com/djangocon/2023.djangocon.us/blob/main/_pages/room-sharing.md

**Comment by blulady** [comment]
https://docs.google.com/spreadsheets/d/1487pyAR--sN3dpSDrDQWAQmxq25BgHIVM99xZIHRpp4/edit?usp=sharing
